# Generated by Django 6.0.5 on 2026-05-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QRToken', models.IntegerField(max_length=1000, unique=True)),
                ('studentName', models.CharField(max_length=100)),
                ('ActivityCompleted_Penalty', models.BooleanField(default=False)),
                ('ActivityCompleted_Keepy', models.BooleanField(default=False)),
                ('ActivityCompleted_Sponges', models.BooleanField(default=False)),
                ('isValid', models.BooleanField(default=True)),
                ('TimeStamp', models.TimeField()),
            ],
        ),
    ]
