# Generated by Django 6.0.5 on 2026-05-15 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRCode_Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(max_length=1000, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('year_group', models.CharField(max_length=10)),
                ('paid_penalty', models.BooleanField(default=False)),
                ('paid_keepy', models.BooleanField(default=False)),
                ('paid_sponges', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='DayTicket',
        ),
        migrations.AddField(
            model_name='scanlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRCode_Main.student'),
        ),
    ]
