# Generated by Django 6.0.5 on 2026-05-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRCode_Main', '0002_scanlog_student_delete_dayticket_scanlog_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='paid_keepy',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paid_penalty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paid_sponges',
        ),
        migrations.AddField(
            model_name='student',
            name='form_group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='issued_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_group',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
