# Generated by Django 6.0.5 on 2026-05-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRCode_Main', '0003_logindetails_remove_student_paid_keepy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='password',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='username',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='activity',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_group',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='issued_by',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_group',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
